## Dataset Churn_Model
* This dataset is taken from kaggle and was used in a Udemy course 
* A bank is investigating a very high rate of customer leaving the bank. Here is a **10,000** records dataset to investigate and predict which of the customers are more likely to leave the bank soon.

### Columns
* RowNumber	
* CustomerId
* Surname
* CreditScore
* Geography
* Gender
* Age
* Tenure
* Balance
* NumOfProducts
* HasCrCard
* IsActiveMember
* EstimatedSalary
* Exited

In [40]:
import pandas as pd
import pickle

In [41]:
data = pd.read_csv('Churn_Modelling.csv')
display(data)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [44]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

## Feature Engineering

In [45]:
# droping unwanted colums [RowNumber, CustomerId, CreditScore ] 
# becase they will not contribute much in the learning process

data = data.drop(['RowNumber', 'CustomerId'], axis = 1)

In [46]:
data

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [47]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [48]:
# Encoding Gender
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
data['Gender'] = le.fit_transform(data.Gender)

In [49]:
data['Gender']

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int32

In [50]:
# OHE Geography Column
from sklearn.preprocessing import OneHotEncoder
oe= OneHotEncoder()
geo_encoded = oe.fit_transform(data[['Geography']]).toarray()
geo_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [51]:
oe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [52]:
geo_df = pd.DataFrame(geo_encoded,columns=oe.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [53]:
data = pd.concat([data.drop('Geography',axis = 1),geo_df], axis = 1)
data.head()

,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,Hargrave,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,Hill,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,Onio,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,Boni,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,Mitchell,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [54]:
# saving encoders and scalers
with open('encoder_gender.pkl','wb') as file:
    pickle.dump(le , file)

with open('encoder_geo.pkl','wb') as file:
    pickle.dump(oe , file)

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# spliting dataset

X =  data.drop(['Exited','Surname'], axis=1)
y = data['Exited']

# train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2, random_state= 42)

# scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [56]:
print(scaler.feature_names_in_)

['CreditScore' 'Gender' 'Age' 'Tenure' 'Balance' 'NumOfProducts'
 'HasCrCard' 'IsActiveMember' 'EstimatedSalary' 'Geography_France'
 'Geography_Germany' 'Geography_Spain']

In [57]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

## ANN Implementation

In [58]:
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [59]:
model = Sequential([
    Dense(64, activation='relu', input_shape = (X_train.shape[1],)),
    Dense(48, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [60]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 48)                3120

 dense_5 (Dense)             (None, 1)                 49

=================================================================
Total params: 4001 (15.63 KB)
Trainable params: 4001 (15.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [61]:
optimize = tensorflow.keras.optimizers.Adam(learning_rate= 0.001)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [62]:
# Model Compilation
model.compile(optimizer= optimize, loss="binary_crossentropy",metrics= ['accuracy'])

In [63]:
# Setting Tensorboard
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tf_callback = TensorBoard(log_dir= log_dir, histogram_freq=1)

In [64]:
# Early stop
early_stop = EarlyStopping(monitor='accuracy', patience= 20, restore_best_weights= True)

In [65]:
#  Train Model
history = model.fit(
    X_train, y_train, validation_data = (X_test,y_test), epochs = 100, 
    callbacks = [tf_callback, early_stop]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.4552 - accuracy: 0.7935 - val_loss: 0.3972 - val_accuracy: 0.8285
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3836 - accuracy: 0.8411 - val_loss: 0.3603 - val_accuracy: 0.8500
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3519 - accuracy: 0.8580 - val_loss: 0.3496 - val_accuracy: 0.8580
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3411 - accuracy: 0.8583 - val_loss: 0.3453 - val_accuracy: 0.8605
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8606 - val_loss: 0.3412 - val_accuracy: 0.8645
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3324 - accuracy: 0.8630 - val_loss: 0.3417 - val_accuracy: 0.8615
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3302 - accuracy: 0.8645 - val_loss: 0.3472 - val_accuracy: 0.8595
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3265 - accuracy: 0.8650 - val_loss: 0.3463 - val_accuracy: 0.8565
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3255 - accuracy: 0.8633 - val_loss: 0.3447 - val_accuracy: 0.8625
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3225 - accuracy: 0.8646 - val_loss: 0.3444 - val_accuracy: 0.8595
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8633 - val_loss: 0.3422 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3183 - accuracy: 0.8671 - val_loss: 0.3384 - val_accuracy: 0.8650
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3168 - accuracy: 0.8679 - val_loss: 0.3425 - val_accuracy: 0.8635
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3149 - accuracy: 0.8675 - val_loss: 0.3500 - val_accuracy: 0.8565
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8681 - val_loss: 0.3429 - val_accuracy: 0.8615
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3115 - accuracy: 0.8689 - val_loss: 0.3558 - val_accuracy: 0.8570
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3087 - accuracy: 0.8717 - val_loss: 0.3416 - val_accuracy: 0.8645
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3089 - accuracy: 0.8694 - val_loss: 0.3440 - val_accuracy: 0.8570
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3083 - accuracy: 0.8721 - val_loss: 0.3443 - val_accuracy: 0.8655
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3056 - accuracy: 0.8712 - val_loss: 0.3419 - val_accuracy: 0.8605
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3036 - accuracy: 0.8729 - val_loss: 0.3474 - val_accuracy: 0.8605
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3022 - accuracy: 0.8759 - val_loss: 0.3479 - val_accuracy: 0.8645
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2997 - accuracy: 0.8751 - val_loss: 0.3469 - val_accuracy: 0.8615
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3003 - accuracy: 0.8720 - val_loss: 0.3513 - val_accuracy: 0.8580
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2981 - accuracy: 0.8773 - val_loss: 0.3506 - val_accuracy: 0.8615
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2970 - accuracy: 0.8764 - val_loss: 0.3496 - val_accuracy: 0.8590
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2950 - accuracy: 0.8761 - val_loss: 0.3509 - val_accuracy: 0.8630
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2931 - accuracy: 0.8775 - val_loss: 0.3549 - val_accuracy: 0.8555
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2928 - accuracy: 0.8794 - val_loss: 0.3533 - val_accuracy: 0.8535
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2918 - accuracy: 0.8786 - val_loss: 0.3511 - val_accuracy: 0.8610
Epoch 31/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2897 - accuracy: 0.8789 - val_loss: 0.3533 - val_accuracy: 0.8520
Epoch 32/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2886 - accuracy: 0.8785 - val_loss: 0.3554 - val_accuracy: 0.8570
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2869 - accuracy: 0.8816 - val_loss: 0.3548 - val_accuracy: 0.8625
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2877 - accuracy: 0.8805 - val_loss: 0.3553 - val_accuracy: 0.8605
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2836 - accuracy: 0.8831 - val_loss: 0.3526 - val_accuracy: 0.8605
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2821 - accuracy: 0.8820 - val_loss: 0.3607 - val_accuracy: 0.8590
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2823 - accuracy: 0.8838 - val_loss: 0.3590 - val_accuracy: 0.8570
Epoch 38/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2794 - accuracy: 0.8840 - val_loss: 0.3615 - val_accuracy: 0.8590
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2803 - accuracy: 0.8834 - val_loss: 0.3614 - val_accuracy: 0.8605
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2783 - accuracy: 0.8838 - val_loss: 0.3683 - val_accuracy: 0.8540
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2771 - accuracy: 0.8855 - val_loss: 0.3584 - val_accuracy: 0.8630
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2751 - accuracy: 0.8869 - val_loss: 0.3629 - val_accuracy: 0.8495
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2730 - accuracy: 0.8888 - val_loss: 0.3646 - val_accuracy: 0.8610
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2725 - accuracy: 0.8831 - val_loss: 0.3624 - val_accuracy: 0.8640
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2726 - accuracy: 0.8874 - val_loss: 0.3749 - val_accuracy: 0.8610
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2697 - accuracy: 0.8892 - val_loss: 0.3687 - val_accuracy: 0.8580
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2685 - accuracy: 0.8885 - val_loss: 0.3728 - val_accuracy: 0.8530
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2691 - accuracy: 0.8886 - val_loss: 0.3643 - val_accuracy: 0.8615
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2667 - accuracy: 0.8903 - val_loss: 0.3674 - val_accuracy: 0.8590
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2674 - accuracy: 0.8871 - val_loss: 0.3685 - val_accuracy: 0.8630
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2639 - accuracy: 0.8903 - val_loss: 0.3691 - val_accuracy: 0.8560
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2630 - accuracy: 0.8906 - val_loss: 0.3709 - val_accuracy: 0.8590
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2615 - accuracy: 0.8885 - val_loss: 0.3752 - val_accuracy: 0.8550
Epoch 54/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2609 - accuracy: 0.8910 - val_loss: 0.3721 - val_accuracy: 0.8575
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2606 - accuracy: 0.8924 - val_loss: 0.3813 - val_accuracy: 0.8535
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2592 - accuracy: 0.8936 - val_loss: 0.3828 - val_accuracy: 0.8490
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2589 - accuracy: 0.8916 - val_loss: 0.3725 - val_accuracy: 0.8575
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2558 - accuracy: 0.8921 - val_loss: 0.3759 - val_accuracy: 0.8555
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2551 - accuracy: 0.8954 - val_loss: 0.3804 - val_accuracy: 0.8485
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2564 - accuracy: 0.8955 - val_loss: 0.3817 - val_accuracy: 0.8570
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2531 - accuracy: 0.8930 - val_loss: 0.3868 - val_accuracy: 0.8530
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2518 - accuracy: 0.8956 - val_loss: 0.3798 - val_accuracy: 0.8520
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2513 - accuracy: 0.8945 - val_loss: 0.3832 - val_accuracy: 0.8535
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2500 - accuracy: 0.8961 - val_loss: 0.3849 - val_accuracy: 0.8490
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2500 - accuracy: 0.8967 - val_loss: 0.3891 - val_accuracy: 0.8570
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2511 - accuracy: 0.8947 - val_loss: 0.3879 - val_accuracy: 0.8495
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2479 - accuracy: 0.8945 - val_loss: 0.3874 - val_accuracy: 0.8530
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2465 - accuracy: 0.8960 - val_loss: 0.3868 - val_accuracy: 0.8480
Epoch 69/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2450 - accuracy: 0.8979 - val_loss: 0.3956 - val_accuracy: 0.8410
Epoch 70/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2448 - accuracy: 0.8961 - val_loss: 0.3908 - val_accuracy: 0.8545
Epoch 71/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2438 - accuracy: 0.8995 - val_loss: 0.3844 - val_accuracy: 0.8575
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2450 - accuracy: 0.8974 - val_loss: 0.3901 - val_accuracy: 0.8550
Epoch 73/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2429 - accuracy: 0.8989 - val_loss: 0.3918 - val_accuracy: 0.8545
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2419 - accuracy: 0.8963 - val_loss: 0.3927 - val_accuracy: 0.8445
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2421 - accuracy: 0.8974 - val_loss: 0.3912 - val_accuracy: 0.8545
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2403 - accuracy: 0.8984 - val_loss: 0.4004 - val_accuracy: 0.8445
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2379 - accuracy: 0.8999 - val_loss: 0.4013 - val_accuracy: 0.8515
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2369 - accuracy: 0.9010 - val_loss: 0.4061 - val_accuracy: 0.8535
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2357 - accuracy: 0.9013 - val_loss: 0.3985 - val_accuracy: 0.8495
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2360 - accuracy: 0.8992 - val_loss: 0.4055 - val_accuracy: 0.8520
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2350 - accuracy: 0.8976 - val_loss: 0.4166 - val_accuracy: 0.8545
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2333 - accuracy: 0.8996 - val_loss: 0.4040 - val_accuracy: 0.8440
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2327 - accuracy: 0.9016 - val_loss: 0.4044 - val_accuracy: 0.8460
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2299 - accuracy: 0.9054 - val_loss: 0.4095 - val_accuracy: 0.8455
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2312 - accuracy: 0.9038 - val_loss: 0.4099 - val_accuracy: 0.8470
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2305 - accuracy: 0.9020 - val_loss: 0.4052 - val_accuracy: 0.8525
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2290 - accuracy: 0.9020 - val_loss: 0.4119 - val_accuracy: 0.8450
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2291 - accuracy: 0.9035 - val_loss: 0.4076 - val_accuracy: 0.8495
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2276 - accuracy: 0.9062 - val_loss: 0.4127 - val_accuracy: 0.8475
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2281 - accuracy: 0.9031 - val_loss: 0.4152 - val_accuracy: 0.8540
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2260 - accuracy: 0.9053 - val_loss: 0.4099 - val_accuracy: 0.8550
Epoch 92/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2231 - accuracy: 0.9075 - val_loss: 0.4145 - val_accuracy: 0.8490
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2259 - accuracy: 0.9013 - val_loss: 0.4176 - val_accuracy: 0.8550
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2246 - accuracy: 0.9056 - val_loss: 0.4201 - val_accuracy: 0.8420
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2219 - accuracy: 0.9059 - val_loss: 0.4242 - val_accuracy: 0.8450
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2200 - accuracy: 0.9089 - val_loss: 0.4531 - val_accuracy: 0.8170
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2210 - accuracy: 0.9095 - val_loss: 0.4218 - val_accuracy: 0.8495
Epoch 98/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2192 - accuracy: 0.9079 - val_loss: 0.4243 - val_accuracy: 0.8530
Epoch 99/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2204 - accuracy: 0.9096 - val_loss: 0.4216 - val_accuracy: 0.8465
Epoch 100/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2161 - accuracy: 0.9096 - val_loss: 0.4246 - val_accuracy: 0.8515

In [66]:
model.save('model.h5')

c:\Coding Ground\Projects\Deep learning ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [67]:
# Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [68]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 9184), started 1 day, 0:22:53 ago. (Use '!kill 9184' to kill it.)